language: php

php:
  - 5.6
  
cache:
  directories:
    - vendor

services:
  - mysql

install:
  - composer install --no-interaction
  - mysql -u root -e "CREATE DATABASE forumam_test";


script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

notifications:
  slack:
    rooms:
      - $SLACK_NOTIF
    on_success: change
    on_failure: change